"""Phase 3: Ledger and Snapshot tables

Revision ID: 313f551cee8c
Revises: 43a014ad94b8
Create Date: 2026-03-10 19:44:23.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '313f551cee8c'
down_revision = '43a014ad94b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ledger_batches table
    op.create_table(
        'ledger_batches',
        sa.Column('batch_id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('portfolio_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('portfolio.portfolio_id'), nullable=False),
        sa.Column('submitted_by_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('user.user_id'), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('meta', postgresql.JSONB(), nullable=True),
        sa.Column('idempotency_key', sa.String(), nullable=True),
    )
    
    # Create index on ledger_batches
    op.create_index(
        'ix_ledger_batches_portfolio_created',
        'ledger_batches',
        ['portfolio_id', 'created_at'],
        postgresql_where=sa.text('portfolio_id IS NOT NULL')
    )
    
    # Create partial unique index for idempotency (only where idempotency_key is not null)
    op.create_index(
        'uq_ledger_batch_idempotency',
        'ledger_batches',
        ['portfolio_id', 'idempotency_key'],
        unique=True,
        postgresql_where=sa.text('idempotency_key IS NOT NULL')
    )
    
    # Create ledger_entries table
    op.create_table(
        'ledger_entries',
        sa.Column('entry_id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('batch_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('ledger_batches.batch_id'), nullable=False),
        sa.Column('portfolio_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('portfolio.portfolio_id'), nullable=False),
        sa.Column('entry_kind', sa.String(), nullable=False),
        sa.Column('effective_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('listing_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('listing.listing_id'), nullable=True),
        sa.Column('quantity_delta', sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column('net_cash_delta_gbp', sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column('fee_gbp', sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column('book_cost_delta_gbp', sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column('reversal_of_entry_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('ledger_entries.entry_id'), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('meta', postgresql.JSONB(), nullable=True),
    )
    
    # Create indexes on ledger_entries
    op.create_index(
        'ix_ledger_entries_portfolio_effective',
        'ledger_entries',
        ['portfolio_id', 'effective_at']
    )
    op.create_index(
        'ix_ledger_entries_batch',
        'ledger_entries',
        ['batch_id']
    )
    op.create_index(
        'ix_ledger_entries_portfolio_listing',
        'ledger_entries',
        ['portfolio_id', 'listing_id', 'effective_at']
    )
    op.create_index(
        'ix_ledger_entries_reversal',
        'ledger_entries',
        ['reversal_of_entry_id']
    )
    
    # Create check constraints on ledger_entries
    op.create_check_constraint(
        'ck_ledger_entry_kind',
        'ledger_entries',
        sa.text("entry_kind IN ('CONTRIBUTION', 'BUY', 'SELL', 'ADJUSTMENT', 'REVERSAL')")
    )
    op.create_check_constraint(
        'ck_ledger_entry_fee_non_negative',
        'ledger_entries',
        sa.text('fee_gbp IS NULL OR fee_gbp >= 0')
    )
    
    # Create cash_snapshots table
    op.create_table(
        'cash_snapshots',
        sa.Column('portfolio_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('portfolio.portfolio_id'), primary_key=True),
        sa.Column('balance_gbp', sa.Numeric(precision=28, scale=10), nullable=False, server_default='0'),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('last_entry_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('ledger_entries.entry_id'), nullable=True),
        sa.Column('version_no', sa.Numeric(precision=20, scale=0), nullable=False, server_default='0'),
    )
    
    # Create holding_snapshots table
    op.create_table(
        'holding_snapshots',
        sa.Column('portfolio_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('portfolio.portfolio_id'), primary_key=True, autoincrement=False),
        sa.Column('listing_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('listing.listing_id'), primary_key=True, autoincrement=False),
        sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False, server_default='0'),
        sa.Column('book_cost_gbp', sa.Numeric(precision=28, scale=10), nullable=False, server_default='0'),
        sa.Column('avg_cost_gbp', sa.Numeric(precision=28, scale=10), nullable=False, server_default='0'),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('last_entry_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('ledger_entries.entry_id'), nullable=True),
        sa.Column('version_no', sa.Numeric(precision=20, scale=0), nullable=False, server_default='0'),
    )
    
    # Create check constraints on holding_snapshots
    op.create_check_constraint(
        'ck_holding_snapshot_quantity_non_negative',
        'holding_snapshots',
        sa.text('quantity >= 0')
    )
    op.create_check_constraint(
        'ck_holding_snapshot_cost_consistency',
        'holding_snapshots',
        sa.text('(quantity = 0 AND book_cost_gbp = 0 AND avg_cost_gbp = 0) OR quantity > 0')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holding_snapshots')
    op.drop_table('cash_snapshots')
    op.drop_table('ledger_entries')
    op.drop_table('ledger_batches')
    # ### end Alembic commands ###
